name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: CI ${{matrix.platform}} ${{matrix.configuration}}
    strategy:
      matrix:
        configuration: [MT, Debug]
        platform: [x64, x86]
        
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        $env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE"
        devenv simple-audio.sln /build "${{matrix.configuration}}|${{matrix.platform}}"
    - name: Test
      run: |
        .build/out-${{matrix.platform}}-${{matrix.configuration}}/simple-audio-test.exe auto
